'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4200
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Scantech.Nissan.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property CommentHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CommentHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ConnectIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ConnectIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DisconnectIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DisconnectIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property EjectNormal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EjectNormal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LedBlack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LedBlack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LedGreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LedGreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LedYellow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LedYellow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property nissanlogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nissanlogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PageUpHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PageUpHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PauseHot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PauseHot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PauseNormal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PauseNormal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PlayHot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PlayHot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PlayNormal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PlayNormal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RecordHot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RecordHot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RecordNormal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RecordNormal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property StepBackwardHotBlue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StepBackwardHotBlue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property StepBackwardNormalBlue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StepBackwardNormalBlue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property StepForwardHotBlue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StepForwardHotBlue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property StepForwardNormalBlue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StepForwardNormalBlue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property StopHotBlue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StopHotBlue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property StopNormalBlue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StopNormalBlue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
